### ISSUE TITLE
The extension is not working

### ISSUE THREAD

**Issue by emreozcan3320** [macro6461/popup-content-script#1]
When i use the extension nothing happens. For example this is your medium page and i used the extention to test it but it didnt worked
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/21045871/236653749-9a4278dd-1cbf-42bb-8d6e-b01b8a4f4019.png">

**Comment by miliu99** [comment]
I got the same problem and was able to figure it out...it's an easy fix by just adding "currentWindow: true" to queryOptions in popup.js:

```
const getCurrentTab = async () => {
    let queryOptions = { active: true, currentWindow: true };
    let [tab] = await chrome.tabs.query(queryOptions);
    return tab;
}
```

**Comment by emreozcan3320** [comment]
@miliu99 Thanks for the answer. Unfortunately, I came up with some other solutions and proceed with development. So I don't have a chance to try your solution.
